name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        rsync -avz --exclude='.git*' -e "ssh -i id_rsa -o StrictHostKeyChecking=no" . root@154.38.180.23:/var/www/myapp
        ssh -i id_rsa -o StrictHostKeyChecking=no root@154.38.180.23 << 'EOF'
          cd /var/www/myapp
          docker-compose down
          docker-compose up -d --build
        EOF
